// build.mjs — 手机端 JSX 预编译
//
// 为什么: 手机端原本用 Babel standalone 在浏览器里现场转译 app.jsx(154KB),
// 每次进页面手机 CPU 都要跑一遍编译器, 加载慢的主因。现在改为本地预编译。
//
// 用法: 改了 app.jsx 或 ../theme-system.js 之后, 在本目录跑:
//   node build.mjs
// 然后把 index.html 里 app.compiled.js?v=N 的 N 手动 +1(破缓存), 一起提交。
//
// 调试快路径: dev.html 保留了旧的浏览器现场编译流程, 改 app.jsx 刷新即生效,
// 不用每次 build; 调完记得跑本脚本让 index.html 跟上。
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ESBUILD = 'npx -y esbuild@0.25.0';
// 顺序有讲究: theme-system 先跑(IIFE 挂 window.OB_THEME/ThemeToggle), app.jsx 再用
const INPUTS = [
  { src: join(here, '..', 'theme-system.js'), loader: 'jsx' },
  { src: join(here, 'app.jsx'), loader: 'jsx' },
];
const OUT = join(here, 'app.compiled.js');

const parts = [];
for (const { src, loader } of INPUTS) {
  const tmp = OUT + '.tmp';
  execSync(
    `${ESBUILD} "${src}" --loader:.js=${loader} --loader:.jsx=${loader} --format=iife --minify --target=es2018 --charset=utf8 --outfile="${tmp}"`,
    { stdio: 'inherit', shell: true },
  );
  parts.push(readFileSync(tmp, 'utf8'));
  rmSync(tmp);
}
const banner = '/* generated by build.mjs — 别手改。源文件: ../theme-system.js + app.jsx */\n';
writeFileSync(OUT, banner + parts.join('\n'));
console.log(`ok -> app.compiled.js (${(banner.length + parts.join('\n').length) / 1024 | 0}KB)`);
